import { type ColumnDef } from '@tanstack/react-table';
import { Badge, Button } from '@/components/ui';
import { Download } from 'lucide-react';
import { createSortableHeader, formatDateTime } from './utils';
import type { Report } from '@/pages/future-work/mock';

const getStatusVariant = (status: Report['status']) => {
  switch (status) {
    case 'completed':
      return 'success';
    case 'pending':
      return 'secondary';
    case 'failed':
      return 'destructive';
    default:
      return 'default';
  }
};

const formatStatus = (status: Report['status']) => {
  return status.charAt(0).toUpperCase() + status.slice(1);
};

export const reportsColumns: ColumnDef<Report>[] = [
  {
    accessorKey: 'reportName',
    header: createSortableHeader('Report Name'),
    cell: ({ row }) => <div className="font-medium">{row.getValue('reportName')}</div>,
  },
  {
    accessorKey: 'reportType',
    header: createSortableHeader('Type'),
    meta: { hideOnMobile: true },
    cell: ({ row }) => <div>{row.getValue('reportType')}</div>,
  },
  {
    accessorKey: 'generatedBy',
    header: createSortableHeader('Generated By'),
    meta: { hideOnMobile: true },
    cell: ({ row }) => <div>{row.getValue('generatedBy')}</div>,
  },
  {
    accessorKey: 'generatedDate',
    header: createSortableHeader('Generated Date'),
    meta: { hideOnMobile: true },
    cell: ({ row }) => {
      const date = row.getValue('generatedDate') as string;
      return <div className="text-sm">{formatDateTime(date)}</div>;
    },
  },
  {
    accessorKey: 'status',
    header: createSortableHeader('Status'),
    cell: ({ row }) => {
      const status = row.getValue('status') as Report['status'];
      return <Badge variant={getStatusVariant(status)}>{formatStatus(status)}</Badge>;
    },
  },
  {
    accessorKey: 'fileSize',
    header: 'File Size',
    meta: { hideOnMobile: true },
    cell: ({ row }) => <div className="text-sm">{row.getValue('fileSize')}</div>,
  },
  {
    id: 'actions',
    header: 'Actions',
    meta: { hideOnMobile: true },
    cell: ({ row }) => {
      const status = row.original.status;
      return (
        <div className="flex items-center gap-2">
          {status === 'completed' && (
            <Button variant="ghost" size="sm" className="h-8">
              <Download className="h-4 w-4 mr-2" />
              Download
            </Button>
          )}
        </div>
      );
    },
  },
];
