/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    /** Root */
    get: operations['root__get'];
  };
  '/auth/login': {
    /**
     * Login
     * @description Authenticate user and return JWT token
     */
    post: operations['login_auth_login_post'];
  };
  '/auth/me': {
    /**
     * Get Current User Info
     * @description Get current authenticated user information
     */
    get: operations['get_current_user_info_auth_me_get'];
  };
  '/patients': {
    /**
     * Get Patients
     * @description Get all patients with their related data (protected endpoint)
     */
    get: operations['get_patients_patients_get'];
  };
  '/health': {
    /** Health Check */
    get: operations['health_check_health_get'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Address */
    Address: {
      /** Street */
      street: string;
      /** City */
      city: string;
      /** State */
      state: string;
      /** Zip Code */
      zip_code: string;
      /**
       * Country
       * @default USA
       */
      country?: string;
      /** Id */
      id: number;
    };
    /** Document */
    Document: {
      /** Title */
      title: string;
      /** Document Type */
      document_type: string;
      /** File Path */
      file_path: string;
      /**
       * Upload Date
       * Format: date
       */
      upload_date: string;
      /** Description */
      description?: string | null;
      /** Id */
      id: number;
    };
    /** EmergencyContact */
    EmergencyContact: {
      /** Name */
      name: string;
      /** Relationship Type */
      relationship_type: string;
      /** Phone */
      phone: string;
      /** Email */
      email?: string | null;
      /** Id */
      id: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** InsuranceInfo */
    InsuranceInfo: {
      /** Provider */
      provider: string;
      /** Policy Number */
      policy_number: string;
      /** Group Number */
      group_number?: string | null;
      /** Effective Date */
      effective_date?: string | null;
      /** Expiration Date */
      expiration_date?: string | null;
      /**
       * Is Primary
       * @default true
       */
      is_primary?: boolean;
      /** Id */
      id: number;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** Medication */
    Medication: {
      /** Name */
      name: string;
      /** Dosage */
      dosage: string;
      /** Frequency */
      frequency: string;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
      /** Prescribing Doctor */
      prescribing_doctor?: string | null;
      /** Id */
      id: number;
    };
    /** Patient */
    Patient: {
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
      /**
       * Date Of Birth
       * Format: date
       */
      date_of_birth: string;
      /** Gender */
      gender?: string | null;
      /** Phone */
      phone?: string | null;
      /** Email */
      email?: string | null;
      /** Medical Record Number */
      medical_record_number: string;
      /** Id */
      id: number;
      /**
       * Addresses
       * @default []
       */
      addresses?: components['schemas']['Address'][];
      /**
       * Emergency Contacts
       * @default []
       */
      emergency_contacts?: components['schemas']['EmergencyContact'][];
      /**
       * Medications
       * @default []
       */
      medications?: components['schemas']['Medication'][];
      /**
       * Insurance Info
       * @default []
       */
      insurance_info?: components['schemas']['InsuranceInfo'][];
      /**
       * Documents
       * @default []
       */
      documents?: components['schemas']['Document'][];
    };
    /** Token */
    Token: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
    };
    /** User */
    User: {
      /** Email */
      email: string;
      /** Role */
      role: string;
      /** Name */
      name: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Root */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  /**
   * Login
   * @description Authenticate user and return JWT token
   */
  login_auth_login_post: {
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Token'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /**
   * Get Current User Info
   * @description Get current authenticated user information
   */
  get_current_user_info_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
  };
  /**
   * Get Patients
   * @description Get all patients with their related data (protected endpoint)
   */
  get_patients_patients_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Patient'][];
        };
      };
    };
  };
  /** Health Check */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
